#### Quick miniconda with numpy, scipy, etc. from ####
# https://conda.io/docs/travis.html               ####
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - sudo apt update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh -O miniconda.sh;
  elif [[ "$TRAVIS_PYTHON_VERSION" == "3.8" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-py38_4.9.2-Linux-x86_64.sh -O miniconda.sh;
  elif [[ "$TRAVIS_PYTHON_VERSION" == "3.8" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh -O miniconda.sh;
  else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - pip install pip --upgrade
  - pip install .
  - pip install coveralls
######################################################
script: 
  - sh test.sh
after_success:
  - coveralls
